name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand({ ping: 1 })' | mongosh"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 5
          --health-start-period 60s

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python for backend
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: |
          cd backend
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
        env:  # Global environment variables for this step
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

      # Debugging secrets
      - name: Debug environment variables
        run: |
          echo "Checking environment variables..."
          echo "MONGO_URI: ${MONGO_URI:+set}"
          echo "JWT_SECRET: ${JWT_SECRET:+set}"
          echo "OPENAI_API_KEY: ${OPENAI_API_KEY:+set}"
          echo "DATABASE_NAME: ${DATABASE_NAME:+set}"
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

      - name: Run backend tests
        run: |
          cd backend
          . venv/bin/activate
          pytest

      # Set up Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      # Build Docker images
      - name: Build Docker Images
        run: docker-compose build

      # Run containers
      - name: Run Docker Containers
        run: |
          docker-compose up -d
          docker ps -a
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          APP_ENV: ${{ secrets.APP_ENV }}

      # Debugging container health
      - name: Debug MongoDB health
        run: |
          echo "Checking MongoDB container health..."
          docker inspect --format='{{json .State.Health}}' $(docker ps -q --filter ancestor=mongo:6.0) || echo "Health check failed"

      # Health Check
      - name: Check App Health
        run: curl -f http://localhost:8000 || exit 1
